### ISSUE TITLE
Main menu is inaccessible when page width <= 1220px

### ISSUE THREAD

**Issue by igor9silva** [lincolixavier/lincolixavier.com#8]
Main menu is inaccessible when page width <= 1220px, including the mobile hamburger menu.

I've tested on macOS Safari and Chrome, and mobile Safari.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/3062866/233861463-626f3081-47db-410f-bf72-631ad487267d.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/3062866/233861472-9d900b4a-0a59-4c5f-b4f2-7f911f1a196f.png">

**Comment by lincolixavier** [comment]
@igor9silva thank you very much, i'm gonna check it out
